# Build stage
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Copy csproj files
COPY HMSAPI/*.csproj HMSAPI/
COPY HMSBAL/*.csproj HMSBAL/
COPY HMSDAL/*.csproj HMSDAL/
COPY HMSMAL/*.csproj HMSMAL/
COPY HMSAPI.sln ./

# Restore
RUN dotnet restore HMSAPI.sln

# Copy everything
COPY . .

# Build & publish
RUN dotnet publish HMSAPI/HMSAPI.csproj -c Release -o /app

# Runtime image
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app .

ENTRYPOINT ["dotnet", "HMSAPI.dll"]
