# BUILD STAGE
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /app

# Copy only csproj files
COPY HMSAPI/*.csproj HMSAPI/
COPY HMSBAL/*.csproj HMSBAL/
COPY HMSDAL/*.csproj HMSDAL/
COPY HMSMAL/*.csproj HMSMAL/

# Restore
RUN dotnet restore

# Copy all source
COPY . .

# Publish API
WORKDIR /app/HMSAPI
RUN dotnet publish -c Release -o out

# RUNTIME
FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app/HMSAPI/out .
EXPOSE 8080
ENTRYPOINT ["dotnet", "HMSAPI.dll"]
