FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build

WORKDIR /app

# Copy solution file
COPY HMSAPI.sln ./

# Copy project files
COPY *.sln ./
COPY HMSAPI/*.csproj ./HMSAPI/
COPY HMSBAL/*.csproj ./HMSBAL/
COPY HMSDAL/*.csproj ./HMSDAL/
COPY HMSMAL/*.csproj ./HMSMAL/

# Restore each project individually
RUN dotnet restore ./HMSAPI/HMSAPI.csproj
RUN dotnet restore ./HMSBAL/HMSBAL.csproj
RUN dotnet restore ./HMSDAL/HMSDAL.csproj
RUN dotnet restore ./HMSMAL/HMSMAL.csproj

RUN ls -R
RUN dotnet restore --verbosity detailed

# Copy all source code
COPY . .

# Build and publish
RUN dotnet publish -c Release -o out
